### ISSUE TITLE
adapt nginx.conf to add delivery of json-files

### ISSUE THREAD

**Issue by philipp-heyse** [anapsix/docker-satisfy#1]
please add json to static delivery filetypes in nginx.conf
i.e: deliver /package.json, which composer will request from the server

https://github.com/anapsix/docker-satisfy/blob/d5b22adc68a651a7e731fdd38f7dd525231353b1/config/nginx.conf#L49

thank you for your work, appreciate it!

**Comment by anapsix** [comment]
apparently done in 632924a85a9ea8eee002cc46474ede4ca7ea74ba
